### ISSUE TITLE
Fee Calculation: executeOrder()

### ISSUE THREAD

**Issue by JaredBorders** [Kwenta/margin-manager#30]
## Description
Issues may arise due to the inability to collect a fee when executeOrder, invoked by ops/gelato, fails due to an insufficient eth balance in the margin account to cover the execution fee. 
Since this type of failure happens during the interaction between the third party and the system, it requires a more thought-out approach. 

## Solution 
For example, having an additional mechanism to update the margin account owner about execution issues related to their pending limit orders

**Comment by JChiaramonte7** [comment]
Didn't see this one until now, but I can enforce an ETH minimum for orders
