### ISSUE TITLE
Factory: Low-Level Issues 

### ISSUE THREAD

**Issue by JaredBorders** [Kwenta/margin-manager#33]
## Description
MarginAccountFactory has no way of enumerating the accounts created and there is no mechanism to confirm a MarginBase instance is created by an authorized MarginAccountFactory.

## Solution
R&D
- [x] Determine IF we should research a way to enumerating the accounts created
- [x] Determine IF we should research a means to confirm that a MarginBase instance is created by an authorized MarginAccountFactory

**Comment by JChiaramonte7** [comment]
We emit an event for this and will be reliant on the subgraph to confirm these things.
