### ISSUE TITLE
Update Deployment Scripts for Goerli

### ISSUE THREAD

**Issue by JaredBorders** [Kwenta/margin-manager#52]
- [x] Update Script with Correct Addresses
- [x] Update hardhat.config
- [x] Update .env (Generate new `ARCHIVE_NODE_URL_KOVAN_L2` for `ARCHIVE_NODE_URL_GOERLI_L2`)
- [x] Update Secrets

**Comment by JChiaramonte7** [comment]
> @JChiaramonte7 you will need to update the secrets for this Repo

Done ✅
