### ISSUE TITLE
(L-3) Settings: Events

### ISSUE THREAD

**Issue by JaredBorders** [Kwenta/margin-manager#75]
## (L-3) TreasuryAddressChanged, TradeFeeChanged, LimitOrderFeeChanged, and StopOrderFeeChanged emit even if the new value is the same as the old one

MarginBaseSettings’s setTreasury(), setTradeFee() , setLimitOrderFee() , and setStopOrderFee() do not check if the new value is different from the old one when emitting their respective events. This creates the potential for duplicate events to be emitted, which may cause confusion to users on the client app, such as displaying a more recent “updated” trade fee when no data has actually changed.

**Comment by JChiaramonte7** [comment]
Not too concerned about this because fees probably won't change that often and will require voting or consensus
