### ISSUE TITLE
(G-1) onlyOwner modifier not needed on depositAndDistribute() function

### ISSUE THREAD

**Issue by JaredBorders** [Kwenta/margin-manager#78]
The `onlyOwner` modifier is not needed on the `depositAndDistribute()` function since the function calls `deposit()` which has its own `onlyOwner` modifier. This means the `onlyOwner` modifier would be called 2 times unnecessarily.

Consider removing the `onlyOwner` modifier on `depositAndDistribute()` to save on gas.

**Comment by JChiaramonte7** [comment]
If we do this, we have to make sure we're really careful not to remove onlyOwner from `deposit` in the future for any reason. 

Or we could create an internal `_deposit` and keep `onlyOwner` on the external `deposit` AND `depositAndDistribute`. (See current pattern for _distributeMargin)
